# Generated by Django 5.2 on 2025-12-02 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_reminderlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, verbose_name='課程代碼')),
                ('course_name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('teacher', models.CharField(blank=True, max_length=50, null=True, verbose_name='授課教師')),
                ('classroom', models.CharField(blank=True, max_length=50, null=True, verbose_name='教室')),
                ('day_of_week', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], max_length=1, verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('credit', models.PositiveSmallIntegerField(default=0, verbose_name='學分數')),
                ('semester', models.CharField(max_length=20, verbose_name='學期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '課程表',
                'verbose_name_plural': '課程表',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CreditSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='學期')),
                ('required_credits', models.PositiveSmallIntegerField(default=0, verbose_name='必修學分')),
                ('elective_credits', models.PositiveSmallIntegerField(default=0, verbose_name='選修學分')),
                ('total_credits', models.PositiveSmallIntegerField(default=0, verbose_name='總學分')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '學分統計',
                'verbose_name_plural': '學分統計',
            },
        ),
        migrations.DeleteModel(
            name='ReminderLog',
        ),
    ]
