# Generated by Django 5.2 on 2025-12-03 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web_app', '0008_courseschedule_creditsummary_delete_reminderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credit_progress', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('required_credits', models.PositiveSmallIntegerField(default=0, verbose_name='必修學分')),
                ('elective_credits', models.PositiveSmallIntegerField(default=0, verbose_name='選修學分')),
                ('major_credits', models.PositiveSmallIntegerField(default=0, verbose_name='專選學分')),
                ('general_credits', models.PositiveSmallIntegerField(default=0, verbose_name='通識學分')),
                ('total_credits', models.PositiveSmallIntegerField(default=0, verbose_name='總學分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '學分進度',
                'verbose_name_plural': '學分進度',
                'db_table': 'web_app_usercreditprogress',
            },
        ),
    ]
