# Generated by Django 5.2 on 2025-12-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_usercreditprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreditprogress',
            name='elective_credits',
        ),
        migrations.RemoveField(
            model_name='usercreditprogress',
            name='general_credits',
        ),
        migrations.RemoveField(
            model_name='usercreditprogress',
            name='major_credits',
        ),
        migrations.RemoveField(
            model_name='usercreditprogress',
            name='required_credits',
        ),
        migrations.AddField(
            model_name='usercreditprogress',
            name='common',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='一般科目'),
        ),
        migrations.AddField(
            model_name='usercreditprogress',
            name='general',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='通識'),
        ),
        migrations.AddField(
            model_name='usercreditprogress',
            name='general_required',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='通識必修'),
        ),
        migrations.AddField(
            model_name='usercreditprogress',
            name='professional_elective',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='專業選修'),
        ),
        migrations.AddField(
            model_name='usercreditprogress',
            name='professional_required',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='專業必修'),
        ),
    ]
