# Generated by Django 5.2 on 2025-12-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_remove_usercreditprogress_elective_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditprogress',
            name='common',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='一般科目'),
        ),
        migrations.AlterField(
            model_name='usercreditprogress',
            name='general',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='通識'),
        ),
        migrations.AlterField(
            model_name='usercreditprogress',
            name='general_required',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='通識必修'),
        ),
        migrations.AlterField(
            model_name='usercreditprogress',
            name='professional_elective',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='專業選修'),
        ),
        migrations.AlterField(
            model_name='usercreditprogress',
            name='professional_required',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='專業必修'),
        ),
        migrations.AlterField(
            model_name='usercreditprogress',
            name='total_credits',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='總學分'),
        ),
    ]
